version: '3.6'
services:
  consul:
    image: consul:1.2.3
    hostname: consul
    ports:
      - 8500:8500
      - 8600:8600
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true, "log_level": "err"}'

  fabio:
    image: magiconair/fabio:1.4.4-go1.8.3
    depends_on:
      - consul
    ports:
      - 9999:9999
      - 9998:9998
    command: ["/fabio",
              "-cfg", "/etc/fabio/fabio.properties",
              "-registry.consul.addr", "consul:8500"]
    volumes:
      - ./fabio.properties:/etc/fabio/fabio.properties

  mongodb:
    image: mongo:3.2.21-jessie
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  web-api-1:
    build:
      context: ../web-api
      dockerfile: Dockerfile
    depends_on:
      - consul
    hostname: web-api-1
    env_file:
      - ../web-api/.env.docker
    environment:
      - CONSUL_HOSTNAME=consul
      - CONSUL_PORT=8500
      - ADVERTISED_HOSTNAME=web-api-1
      - ADVERTISED_PORT=8080
    ports:
      - 8080:8080

  sse-connector-1:
    build:
      context: ../services
      dockerfile: Dockerfile
    depends_on:
      - consul
    hostname: sse-connector-1
    env_file:
      - ../services/.env.docker
    environment:
      - SERVICE_ID=sse-connector-1
      - CONSUL_HOSTNAME=consul
      - CONSUL_PORT=8500
      - ADVERTISED_HOSTNAME=sse-connector-1
      - ADVERTISED_PORT=3838
    ports:
      - 3838:3838